---
abstract: 'Pure perl API for Proxmox virtualisation'
author:
  - 'Brendan Beveridge <brendan@nodeintegration.com.au>, Dean Hamstead <dean@fragfest.com.au>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0
  Test::Trap: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Proxmox-VE
requires:
  Carp: 0
  HTTP::Headers: 0
  HTTP::Request::Common: 0
  JSON: 0
  LWP::UserAgent: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Net-Proxmox-VE
  homepage: https://github.com/mrproper/proxmox-ve-api-perl
  repository: git://github.com/mrproper/proxmox-ve-api-perl.git
version: 0.004
